### ISSUE TITLE
Add Top, Left, Bottom and Right to Rectangle class

### ISSUE THREAD

**Issue by AlanWills** [032MendicantBias/Roguelike#1]
As we discussed, with Rectangles it is quite useful to be able to get the coordinates of the centre of each side (we do not need setters because I don't think that's how we want to drive changing the rectangle's dimensions).

There are a couple of ways you could do this, but I think the nicest might be using a Property for each where the 'get' calculates and returns the coordinates from the Position and Size e.g.

public Vector2 Left
{
    get 
    {
        // put your calculation here
    }
}

This would enforce the fact you can't set it.  If you have another way of doing it, I am all ears

**Comment by JamesChristen** [comment]
Done, you scrub
